"""
Django settings for Tales project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS', cast=list)

CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS', cast=list)


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Proxy arkasındayken HTTPS algılama
SECURE_SSL_REDIRECT = True  # HTTP isteklerini HTTPS'e yönlendirir
SECURE_HSTS_SECONDS = 31536000  # 1 yıl HSTS politikası
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Alt alanları da HSTS politikasına dahil et
SECURE_HSTS_PRELOAD = True  # Tarayıcı HSTS ön yükleme listesine eklenebilme

# Çerez Güvenliği
SESSION_COOKIE_SECURE = True  # Oturum çerezlerini sadece HTTPS üzerinden gönder
CSRF_COOKIE_SECURE = True  # CSRF token çerezlerini sadece HTTPS üzerinden gönder
SESSION_COOKIE_HTTPONLY = True  # JavaScript'in session çerezlerine erişimini engeller
CSRF_COOKIE_HTTPONLY = True  # JavaScript'in CSRF çerezlerine erişimini engeller (API kullanan siteler için False yapın)
SESSION_COOKIE_SAMESITE = 'Lax'   # Üçüncü taraf isteklere kısıtlama getirir :contentReference[oaicite:11]{index=11}
CSRF_COOKIE_SAMESITE    = 'Lax'   # CSRF korumasını güçlendirir :contentReference[oaicite:12]{index=12}


# İçerik Güvenliği
SECURE_CONTENT_TYPE_NOSNIFF = True  # Tarayıcının içerik tipini tahmin etmesini engeller (XSS koruması)
SECURE_BROWSER_XSS_FILTER = True  # Tarayıcıların XSS korumasını etkinleştirir
SECURE_REFERRER_POLICY = 'same-origin'  # Referer bilgisini sınırla :contentReference[oaicite:15]{index=15}
# Tarayıcıların sayfayı bir frame veya iframe içinde göstermesini engeller (Clickjacking koruması).
# 'DENY' (hiçbir zaman) veya 'SAMEORIGIN' (sadece kendi sitenizden) seçenekleri vardır.
# 'SAMEORIGIN' genellikle daha kullanışlıdır.
X_FRAME_OPTIONS = 'SAMEORIGIN' # veya 'DENY'

# Form verileri sınırlamaları
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Formda izin verilen maksimum alan sayısı
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # Yükleme bellek limiti (5MB)

# Oturum güvenliği
#SESSION_COOKIE_AGE = 1209600  # Oturum süresi (2 hafta / saniye cinsinden)
#SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Tarayıcı kapandığında oturumun sonlanmaması



# Application definition


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'Masallar.apps.MasallarConfig',
    "ckeditor",
    "django.contrib.sitemaps",
    "whitenoise.runserver_nostatic",
    "storages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]




ROOT_URLCONF = "Tales.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Tales.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": BASE_DIR / "db.sqlite3",
#    }
#}


DATABASES = {
    "default": env.db()
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


if DEBUG:
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'static'

    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'Masallar/static'),
    ]

    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
else:
    #AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    #AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    #AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    #AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')

    AWS_ACCESS_KEY_ID = env('cf_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('cf_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('cf_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env('R2_ENDPOINT_URL')

    DEFAULT_FILE_STORAGE = 'resume.custom_storages.MediaStorage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_IS_GZIPPED = True  # ✅ S3'te otomatik GZip

    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_OBJECT_PARAMETERS = {
        'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
        'CacheControl': 'max-age=94608000',
    }

    STATICFILES_LOCATION = 'static'
    AWS_LOCATION = 'static'
    #AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_CUSTOM_DOMAIN = 'cdn.kidsstorieshub.com'  # Cloudflare üzerinden
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATICFILES_LOCATION}/'
    STATIC_ROOT = STATIC_URL

    MEDIA_LOCATION = 'media'
    IMAGE_SETTING_LOCATION = MEDIA_LOCATION + '/image_settings'
    DOCUMENT_LOCATION = MEDIA_LOCATION + '/documents'

    # GZIP sıkıştırma aktif
    AWS_IS_GZIPPED = True
    GZIP_CONTENT_TYPES = [
        'text/css',
        'application/javascript',
        'image/svg+xml'
    ]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 600,
        'width': 900,
    },
}
