# Generated by Django 4.2.6 on 2023-10-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Masallar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storycategory", options={"verbose_name_plural": "Story Category"},
        ),
        migrations.RenameField(
            model_name="storycategory", old_name="HikayeKategoriAdi", new_name="Title",
        ),
        migrations.RenameField(
            model_name="storycategory", old_name="HikayeSlug", new_name="slug",
        ),
        migrations.RemoveField(model_name="storycategory", name="Hikaye_Title",),
        migrations.AddField(
            model_name="storycategory",
            name="H1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
