# Generated by Django 4.2.6 on 2023-10-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Masallar", "0002_alter_storycategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="resim_name",
            field=models.CharField(
                help_text="Masal Hiyenin başlığını girin.", max_length=255, null=True
            ),
        ),
    ]
