# Generated by Django 4.2.6 on 2023-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Masallar", "0003_story_resim_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="storycategory",
            name="short_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
