# Generated by Django 4.2.6 on 2023-11-08 23:30

import Masallar.models
import Tales.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Masallar", "0005_blog"),
    ]

    operations = [
        migrations.RemoveField(model_name="story", name="resim_name",),
        migrations.AddField(
            model_name="story",
            name="resim",
            field=models.ImageField(
                blank=True,
                help_text="Anasayfa Resim",
                null=True,
                storage=Tales.custom_storages.ImageSettingStorage(),
                upload_to=Masallar.models.kapak_resmi_upload_to,
            ),
        ),
    ]
