# Generated by Django 4.2.6 on 2023-11-09 00:00

import Masallar.models
import Tales.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Masallar", "0006_remove_story_resim_name_story_resim"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="resim",
            field=models.ImageField(
                blank=True,
                help_text="Anasayfa Resim",
                null=True,
                storage=Tales.custom_storages.ImageSettingStorage(),
                upload_to=Masallar.models.kapak_resmi_upload_to,
            ),
        ),
    ]
