# Generated by Django 4.2.6 on 2023-11-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Masallar", "0007_blog_resim"),
    ]

    operations = [
        migrations.CreateModel(
            name="iletisimmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                (
                    "icerik",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        null=True,
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name_plural": "iletişim Formu",},
        ),
    ]
